FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir streamlit pandas plotly pydantic openpyxl
COPY . /app
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
